### PR TITLE
Fix links between league and match rules

### PR DESCRIPTION
**Pull request by Invader-Zim**
I can't confirm the links work.  The URL on the site does not have the HTML extension, but actual files do.  I'm not sure why that works on the site.

### CODE REVIEW

**Comment by geoffsimons** [comment]
If I were to merge this PR, it would destroy the pretty printing that exists in the files. Can you just edit the lines with the links that need to be updated?

**Comment by Invader-Zim** [comment]
Oh, the coloring is backward.  I thought MINE had the nice formatting, and the original had no line breaks.  I'll fix it.

**Comment by Invader-Zim** [comment]
I have verified that MINE is the one with the nice formatting.  The one in the main branch has no line breaks.

**Comment by geoffsimons** [comment]
I stand corrected. Merging.

**Pull request merged**
